/**
 * generated by Xtext 2.36.0
 */
package org.xtext.example.mydsl.myDsl.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.example.mydsl.myDsl.Action;
import org.xtext.example.mydsl.myDsl.Item;
import org.xtext.example.mydsl.myDsl.Location;
import org.xtext.example.mydsl.myDsl.Model;
import org.xtext.example.mydsl.myDsl.MyDslPackage;
import org.xtext.example.mydsl.myDsl.NPC;
import org.xtext.example.mydsl.myDsl.Player;
import org.xtext.example.mydsl.myDsl.Quest;
import org.xtext.example.mydsl.myDsl.Story;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.ModelImpl#getStory <em>Story</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.ModelImpl#getPlayer <em>Player</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.ModelImpl#getLocations <em>Locations</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.ModelImpl#getNpc <em>Npc</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.ModelImpl#getItem <em>Item</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.ModelImpl#getAction <em>Action</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.ModelImpl#getQuest <em>Quest</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ModelImpl extends MinimalEObjectImpl.Container implements Model
{
  /**
   * The cached value of the '{@link #getStory() <em>Story</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getStory()
   * @generated
   * @ordered
   */
  protected Story story;

  /**
   * The cached value of the '{@link #getPlayer() <em>Player</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPlayer()
   * @generated
   * @ordered
   */
  protected Player player;

  /**
   * The cached value of the '{@link #getLocations() <em>Locations</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLocations()
   * @generated
   * @ordered
   */
  protected EList<Location> locations;

  /**
   * The cached value of the '{@link #getNpc() <em>Npc</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNpc()
   * @generated
   * @ordered
   */
  protected EList<NPC> npc;

  /**
   * The cached value of the '{@link #getItem() <em>Item</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getItem()
   * @generated
   * @ordered
   */
  protected EList<Item> item;

  /**
   * The cached value of the '{@link #getAction() <em>Action</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAction()
   * @generated
   * @ordered
   */
  protected EList<Action> action;

  /**
   * The cached value of the '{@link #getQuest() <em>Quest</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getQuest()
   * @generated
   * @ordered
   */
  protected EList<Quest> quest;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ModelImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.MODEL;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Story getStory()
  {
    return story;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetStory(Story newStory, NotificationChain msgs)
  {
    Story oldStory = story;
    story = newStory;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyDslPackage.MODEL__STORY, oldStory, newStory);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setStory(Story newStory)
  {
    if (newStory != story)
    {
      NotificationChain msgs = null;
      if (story != null)
        msgs = ((InternalEObject)story).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.MODEL__STORY, null, msgs);
      if (newStory != null)
        msgs = ((InternalEObject)newStory).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.MODEL__STORY, null, msgs);
      msgs = basicSetStory(newStory, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.MODEL__STORY, newStory, newStory));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Player getPlayer()
  {
    return player;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetPlayer(Player newPlayer, NotificationChain msgs)
  {
    Player oldPlayer = player;
    player = newPlayer;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyDslPackage.MODEL__PLAYER, oldPlayer, newPlayer);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setPlayer(Player newPlayer)
  {
    if (newPlayer != player)
    {
      NotificationChain msgs = null;
      if (player != null)
        msgs = ((InternalEObject)player).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.MODEL__PLAYER, null, msgs);
      if (newPlayer != null)
        msgs = ((InternalEObject)newPlayer).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.MODEL__PLAYER, null, msgs);
      msgs = basicSetPlayer(newPlayer, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.MODEL__PLAYER, newPlayer, newPlayer));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Location> getLocations()
  {
    if (locations == null)
    {
      locations = new EObjectContainmentEList<Location>(Location.class, this, MyDslPackage.MODEL__LOCATIONS);
    }
    return locations;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<NPC> getNpc()
  {
    if (npc == null)
    {
      npc = new EObjectContainmentEList<NPC>(NPC.class, this, MyDslPackage.MODEL__NPC);
    }
    return npc;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Item> getItem()
  {
    if (item == null)
    {
      item = new EObjectContainmentEList<Item>(Item.class, this, MyDslPackage.MODEL__ITEM);
    }
    return item;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Action> getAction()
  {
    if (action == null)
    {
      action = new EObjectContainmentEList<Action>(Action.class, this, MyDslPackage.MODEL__ACTION);
    }
    return action;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Quest> getQuest()
  {
    if (quest == null)
    {
      quest = new EObjectContainmentEList<Quest>(Quest.class, this, MyDslPackage.MODEL__QUEST);
    }
    return quest;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MyDslPackage.MODEL__STORY:
        return basicSetStory(null, msgs);
      case MyDslPackage.MODEL__PLAYER:
        return basicSetPlayer(null, msgs);
      case MyDslPackage.MODEL__LOCATIONS:
        return ((InternalEList<?>)getLocations()).basicRemove(otherEnd, msgs);
      case MyDslPackage.MODEL__NPC:
        return ((InternalEList<?>)getNpc()).basicRemove(otherEnd, msgs);
      case MyDslPackage.MODEL__ITEM:
        return ((InternalEList<?>)getItem()).basicRemove(otherEnd, msgs);
      case MyDslPackage.MODEL__ACTION:
        return ((InternalEList<?>)getAction()).basicRemove(otherEnd, msgs);
      case MyDslPackage.MODEL__QUEST:
        return ((InternalEList<?>)getQuest()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyDslPackage.MODEL__STORY:
        return getStory();
      case MyDslPackage.MODEL__PLAYER:
        return getPlayer();
      case MyDslPackage.MODEL__LOCATIONS:
        return getLocations();
      case MyDslPackage.MODEL__NPC:
        return getNpc();
      case MyDslPackage.MODEL__ITEM:
        return getItem();
      case MyDslPackage.MODEL__ACTION:
        return getAction();
      case MyDslPackage.MODEL__QUEST:
        return getQuest();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyDslPackage.MODEL__STORY:
        setStory((Story)newValue);
        return;
      case MyDslPackage.MODEL__PLAYER:
        setPlayer((Player)newValue);
        return;
      case MyDslPackage.MODEL__LOCATIONS:
        getLocations().clear();
        getLocations().addAll((Collection<? extends Location>)newValue);
        return;
      case MyDslPackage.MODEL__NPC:
        getNpc().clear();
        getNpc().addAll((Collection<? extends NPC>)newValue);
        return;
      case MyDslPackage.MODEL__ITEM:
        getItem().clear();
        getItem().addAll((Collection<? extends Item>)newValue);
        return;
      case MyDslPackage.MODEL__ACTION:
        getAction().clear();
        getAction().addAll((Collection<? extends Action>)newValue);
        return;
      case MyDslPackage.MODEL__QUEST:
        getQuest().clear();
        getQuest().addAll((Collection<? extends Quest>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.MODEL__STORY:
        setStory((Story)null);
        return;
      case MyDslPackage.MODEL__PLAYER:
        setPlayer((Player)null);
        return;
      case MyDslPackage.MODEL__LOCATIONS:
        getLocations().clear();
        return;
      case MyDslPackage.MODEL__NPC:
        getNpc().clear();
        return;
      case MyDslPackage.MODEL__ITEM:
        getItem().clear();
        return;
      case MyDslPackage.MODEL__ACTION:
        getAction().clear();
        return;
      case MyDslPackage.MODEL__QUEST:
        getQuest().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.MODEL__STORY:
        return story != null;
      case MyDslPackage.MODEL__PLAYER:
        return player != null;
      case MyDslPackage.MODEL__LOCATIONS:
        return locations != null && !locations.isEmpty();
      case MyDslPackage.MODEL__NPC:
        return npc != null && !npc.isEmpty();
      case MyDslPackage.MODEL__ITEM:
        return item != null && !item.isEmpty();
      case MyDslPackage.MODEL__ACTION:
        return action != null && !action.isEmpty();
      case MyDslPackage.MODEL__QUEST:
        return quest != null && !quest.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //ModelImpl
