/**
 * generated by Xtext 2.36.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Location</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Location#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Location#getNPCs <em>NP Cs</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Location#getItems <em>Items</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Location#getConnections <em>Connections</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getLocation()
 * @model
 * @generated
 */
public interface Location extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getLocation_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Location#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>NP Cs</b></em>' reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl.NPC}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>NP Cs</em>' reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getLocation_NPCs()
   * @model
   * @generated
   */
  EList<NPC> getNPCs();

  /**
   * Returns the value of the '<em><b>Items</b></em>' reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl.Item}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Items</em>' reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getLocation_Items()
   * @model
   * @generated
   */
  EList<Item> getItems();

  /**
   * Returns the value of the '<em><b>Connections</b></em>' reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl.Location}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Connections</em>' reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getLocation_Connections()
   * @model
   * @generated
   */
  EList<Location> getConnections();

} // Location
