/**
 * generated by Xtext 2.36.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Player</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Player#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Player#getActions <em>Actions</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Player#getItems <em>Items</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Player#getAttr <em>Attr</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getPlayer()
 * @model
 * @generated
 */
public interface Player extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getPlayer_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Player#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Actions</b></em>' reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl.Action}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Actions</em>' reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getPlayer_Actions()
   * @model
   * @generated
   */
  EList<Action> getActions();

  /**
   * Returns the value of the '<em><b>Items</b></em>' reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl.Item}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Items</em>' reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getPlayer_Items()
   * @model
   * @generated
   */
  EList<Item> getItems();

  /**
   * Returns the value of the '<em><b>Attr</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl.Attribute}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Attr</em>' containment reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getPlayer_Attr()
   * @model containment="true"
   * @generated
   */
  EList<Attribute> getAttr();

} // Player
