/**
 * generated by Xtext 2.36.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Story</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Story#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Story#getStartLocation <em>Start Location</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getStory()
 * @model
 * @generated
 */
public interface Story extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getStory_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Story#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Start Location</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Start Location</em>' reference.
   * @see #setStartLocation(Location)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getStory_StartLocation()
   * @model
   * @generated
   */
  Location getStartLocation();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Story#getStartLocation <em>Start Location</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Start Location</em>' reference.
   * @see #getStartLocation()
   * @generated
   */
  void setStartLocation(Location value);

} // Story
